public enum RobotTrigger
{
    LineDetected,
    IntersectionDetected,
    NoLineDetected,
    ObstacleTooClose,
    NoObstacles,
    Pause,
    Resume,
    NavigateIntersection,
    FollowBlueLine,
    FinishedNavigatingIntersection,
    CollectBox,
    GrabbedBox,
    ReturnedWithBox,
    DropBox,
    DroppedBox,
    ReturnedFromDropPoint,
}
